### ISSUE TITLE
Axis labels displayed improperly when multiple scenes are vertically stacked.

### ISSUE THREAD

**Issue by tesseralis** [qbead/bloch-sphere#2]
When two Bloch sphere diagrams are rendered vertically, the axis labels are placed over the first scene.

![Image](https://github.com/user-attachments/assets/b0c5ea2e-40f7-4520-b1b0-9718c2a94c3e)

Codepen:
https://codepen.io/tesseralis/pen/vEOQLGo

**Comment by wellcaffeinated** [comment]
Hi @tesseralis !
Good catch. As a quick fix, please add a css rule to the container elements:
```css
#bloch-sphere, #bloch-sphere-2 {
  position: relative;
  width: 600px;
  height: 600px;
}
```
